
import MODELO.Conexão;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lion
 */
public class ExcluirFilme extends javax.swing.JFrame {
static float x;
static float vt;
int d=0;
String datae;
String data;
long intervalo;
    /**
     * Creates new form ExcluirFilme
     */
    public ExcluirFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Excluir Filme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Codigo Filme");

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo da Locação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          PreparedStatement ps;
        try {
            PegarValor();
            pegax();
           
            ps = Conexão.getConexão().prepareStatement("DELETE FROM FILMES_LOCADOS WHERE FILME_COD = ? AND LOCACAO_COD = ?");
                        ps.setString(1, jTextField1.getText());
                        ps.setString(2, jTextField2.getText());
                        ps.executeUpdate();
                        Update();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ExcluirFilme.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Update(){
    vt = vt-(d*x);
    PreparedStatement ps;
    try {
        pegadata();
        ps = Conexão.getConexão().prepareStatement("UPDATE LOCACAO SET VALOR_TOTAL = ?, DATA_ENTREGUE=?, DIARIASL=? WHERE CODIGOL=?");
        ps.setFloat(1, vt);
        ps.setString(2, "");
        ps.setInt(3, (int) intervalo);
        ps.setInt(4, (Integer.parseInt(jTextField2.getText())));
        ps.executeUpdate();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AddF.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    public void pegadata() throws ClassNotFoundException{
PreparedStatement ps;
        try {
            ps = Conexão.getConexão().prepareStatement("SELECT DATA_ENTREGA FROM LOCACAO WHERE CODIGOL=?");
            ps.setInt(1, (Integer.parseInt(jTextField2.getText())));
            ResultSet rs = ps.executeQuery();
            rs.next();
            datae = rs.getString("DATA_ENTREGA");
        } catch (SQLException ex) {
            Logger.getLogger(DevolverF.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps = Conexão.getConexão().prepareStatement("SELECT DATAL FROM LOCACAO WHERE CODIGOL=?");
            ps.setInt(1, (Integer.parseInt(jTextField2.getText())));
            ResultSet rs = ps.executeQuery();
            rs.next();
            data = rs.getString("DATAL");
        } catch (SQLException ex) {
            Logger.getLogger(DevolverF.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dividi[] = data.split("/");
    int ano1= (Integer.parseInt(dividi[2]));
    int mes1= (Integer.parseInt(dividi[1]));
    int dia1= (Integer.parseInt(dividi[0]));
        
    String dividir[] = datae.split("/");
    int ano2= (Integer.parseInt(dividir[2]));
    int mes2= (Integer.parseInt(dividir[1]));
    int dia2= (Integer.parseInt(dividir[0]));
    
    LocalDate inicio = LocalDate.of(ano1, mes1, dia1);
    LocalDate fim = LocalDate.of(ano2, mes2, dia2);
    intervalo = ChronoUnit.DAYS.between(inicio, fim);
}
    
    public void PegarValor(){
PreparedStatement ps;
    try {
        ps = Conexão.getConexão().prepareStatement("SELECT VALOR_TOTAL FROM LOCACAO WHERE CODIGOL=?");
        ps.setInt(1, (Integer.parseInt(jTextField2.getText())));
        ResultSet rs = ps.executeQuery();
        rs.next();
            vt = rs.getFloat("VALOR_TOTAL");
            ps.executeQuery();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AddF.class.getName()).log(Level.SEVERE, null, ex);
    }
            try {
        ps = Conexão.getConexão().prepareStatement("SELECT DIARIASL FROM LOCACAO WHERE CODIGOL=?");
        ps.setInt(1, (Integer.parseInt(jTextField2.getText())));
        ResultSet rs = ps.executeQuery();
        rs.next();
            d = rs.getInt("DIARIASL");
            ps.executeQuery();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AddF.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    public void pegax(){
 //pegando valor de TIPO
    PreparedStatement ps;
    try {
        ps = Conexão.getConexão().prepareStatement("SELECT VALOR_LOCACAOT FROM TIPO WHERE CODIGOT=?");
        ps.setInt(1, (Integer.parseInt(jTextField1.getText())));
        ResultSet rs = ps.executeQuery();
        rs.next();
            x = rs.getFloat("VALOR_LOCACAOT");
            ps.executeQuery();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AddF.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
